
FROM node:lts-alpine AS base
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]


FROM base AS development
ENV NODE_ENV=development
RUN npm install --silent
COPY . .
EXPOSE 5001
CMD ["npm","run","dev"]



FROM base AS production
ENV NODE_ENV=production
RUN npm install --production --silent && mv node_modules ../
COPY . .
EXPOSE 5001
RUN chown -R node /usr/src/app
USER node
CMD ["npm", "start"]
