apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monogodb-pvc
  namespace: ecommerce
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
