apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: ecommerce
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data
    server: 172.17.0.2
